class AppLocalizations {
  static const Map<String, String> th = {
    // Navigation
    'dashboard': 'แดชบอร์ด',
    'statistics': 'สถิติ',
    'goals': 'เป้าหมาย',
    'profile': 'โปรไฟล์',

    // Dashboard
    'goodMorning': 'สวัสดีตอนเช้า',
    'goodAfternoon': 'สวัสดีตอนบ่าย',
    'goodEvening': 'สวัสดีตอนเย็น',
    'gripOverview': 'สรุปแรงบีบมือของคุณ',
    'currentStatus': 'สถานะปัจจุบัน',
    'normal': 'ปกติ',
    'warning': 'ระวัง',
    'risk': 'เสี่ยง',
    'viewDetails': 'ดูรายละเอียด',
    'gripStrength': 'แรงบีบมือ',
    'maxToday': 'สูงสุดวันนี้',
    'brainScore': 'คะแนนสมอง',
    'excellentCognitive': 'สุขภาพสมองดีเยี่ยม',
    'startTraining': 'เริ่มฝึก',
    'todaysProgress': 'ความคืบหน้าวันนี้',
    'rounds': 'รอบ',
    'completed': 'เสร็จสิ้น',

    // Statistics
    'days7': '7 วัน',
    'days30': '30 วัน',
    'days90': '90 วัน',
    'average': 'เฉลี่ย',
    'maximum': 'สูงสุด',
    'trend': 'แนวโน้ม',
    'gripTrend': 'แนวโน้มแรงบีบมือ',
    'insights': 'ข้อมูลเชิงลึก',
    'consistency': 'ความสม่ำเสมอ',
    'trainedDays': 'คุณฝึก {count} วันในช่วงนี้',
    'peakStrength': 'แรงบีบสูงสุด {value} กก.',
    'improved': 'แรงบีบของคุณเพิ่มขึ้น {value}%',
    'keepWorking': 'พยายามต่อไปเพื่อปรับปรุง',

    // Goals
    'turtlePet': 'แมวเลี้ยง',
    'keepTraining': 'ฝึกต่อไปเพื่ออัพเลเวล!',
    'level': 'เลเวล',
    'experience': 'ประสบการณ์',
    'toNextLevel': 'ถึงเลเวลถัดไป',
    'dailyTasks': 'ภารกิจประจำวัน',
    'gripExercise': 'ฝึกบีบมือ 3 ครั้ง',
    'audioRhythm': 'ฝึกจังหวะเสียง',
    'consecutiveTraining': 'ฝึกต่อเนื่อง',

    // Profile
    'personalInfo': 'ข้อมูลส่วนตัว',
    'name': 'ชื่อ',
    'age': 'อายุ',
    'memberSince': 'สมาชิกตั้งแต่',
    'totalSessions': 'เซสชันทั้งหมด',
    'notifications': 'การแจ้งเตือน',
    'trainingReminders': 'แจ้งเตือนฝึก',
    'dailyGoals': 'เป้าหมายรายวัน',
    'weeklyReports': 'รายงานรายสัปดาห์',
    'caregiver': 'ผู้ดูแล',
    'primaryCaregiver': 'ผู้ดูแลหลัก',
    'settings': 'ตั้งค่า',
    'darkMode': 'โหมดมืด',
    'helpSupport': 'ช่วยเหลือ',
    'about': 'เกี่ยวกับ',
    'features': 'ฟีเจอร์',
    'logout': 'ออกจากระบบ',
    'logoutConfirm': 'คุณต้องการออกจากระบบจริงหรือ?',
    'cancel': 'ยกเลิก',

    // Settings
    'account': 'บัญชี',
    'editProfile': 'แก้ไขโปรไฟล์',
    'editProfileDesc': 'เปลี่ยนข้อมูลส่วนตัว',
    'changePassword': 'เปลี่ยนรหัสผ่าน',
    'changePasswordDesc': 'อัพเดทรหัสผ่าน',
    'notificationPrefs': 'ตั้งค่าการแจ้งเตือน',
    'notificationPrefsDesc': 'จัดการการแจ้งเตือน',
    'trainingReminder': 'แจ้งเตือนฝึก',
    'trainingReminderDesc': 'ตั้งค่าแจ้งเตือนฝึก',
    'appearance': 'รูปลักษณ์',
    'data': 'ข้อมูล',
    'backupData': 'สำรองข้อมูล',
    'backupDesc': 'สำรองข้อมูลการฝึก',
    'restoreData': 'กู้คืนข้อมูล',
    'restoreDesc': 'กู้คืนจากสำเนา',
    'exportData': 'ส่งออกข้อมูล',
    'exportDesc': 'ส่งออกเป็น CSV',
    'support': 'การสนับสนุน',
    'helpAndSupport': 'ช่วยเหลือและสนับสนุน',
    'termsOfService': 'ข้อกำหนดการใช้งาน',
    'privacyPolicy': 'นโยบายความเป็นส่วนตัว',
    'appVersion': 'เวอร์ชันแอป 1.0.0',
    'dangerZone': 'โซนอันตราย',
    'deleteAccount': 'ลบบัญชี',
    'deleteConfirm': 'คุณแน่ใจหรือว่าต้องการลบบัญชี? การกระทำนี้ไม่สามารถย้อนกลับได้',

    // Smart Rhythm
    'smartRhythm': 'ฝึกจังหวะอัจฉริยะ',
    'play': 'เล่น',
    'pause': 'หยุดชั่วคราว',
    'resume': 'เล่นต่อ',
    'stop': 'หยุด',
    'speed': 'ความเร็ว',
    'slow': 'ช้า',
    'medium': 'ปานกลาง',
    'fast': 'เร็ว',
    'beats': 'จังหวะ',
    'completedBeats': 'จังหวะที่ทำเสร็จ',

    // Measurement
    'gripMeasurement': 'วัดแรงบีบมือ',
    'today': 'วันนี้',
    'quickActions': 'เข้าถึงด่วน',
    'startMeasurement': 'เริ่มวัด',
    'measurementComplete': 'วัดเสร็จสิ้น',
    'measureAgain': 'วัดอีกครั้ง',
    'backToHome': 'กลับหน้าหลัก',
    'pressToStart': 'กดปุ่มเริ่มเพื่อวัดแรงบีบมือ',
    'maxGrip': 'สูงสุด',
    'minGrip': 'ต่ำสุด',
    'time': 'เวลา',
    'duration': 'ระยะเวลา',
    'details': 'รายละเอียด',
    'averageGrip': 'ค่าเฉลี่ย',

    // Streak
    'streakCalendar': 'ปฏิทินความต่อเนื่อง',
    'currentStreak': 'ต่อเนื่องตอนนี้',
    'longestStreak': 'ต่อเนื่องนานสุด',
    'days': 'วัน',
    'trainingDays': 'วันที่ฝึก',
    'streakTip': 'ฝึกทุกวันเพื่อรักษาความต่อเนื่อง ยิ่งฝึกนาน ยิ่งได้รางวัล!',

    // History
    'trainingHistory': 'ประวัติการฝึก',
    'allSessions': 'ทุกเซสชัน',
    'gripSession': 'ฝึกบีบมือ',
    'rhythmSession': 'ฝึกจังหวะ',
    'guidedSession': 'ฝึกแนะนำ',
    'sessions': 'เซสชัน',
    'noHistory': 'ยังไม่มีประวัติการฝึก',

    // Report
    'healthReport': 'รายงานสุขภาพ',
    'weeklyReport': 'รายงานรายสัปดาห์',
    'monthlyReport': 'รายงานรายเดือน',
    'comparison': 'การเปรียบเทียบ',
    'thisWeek': 'สัปดาห์นี้',
    'lastWeek': 'สัปดาห์ที่แล้ว',
    'improvement': 'ปรับปรุง',
    'decline': 'ลดลง',
    'shareReport': 'แชร์รายงาน',
    'trainedDaysThisWeek': 'คุณฝึก 5 วันในสัปดาห์นี้',
    'gripImproved': 'แรงบีบเพิ่มขึ้น 5.2% จากสัปดาห์ที่แล้ว',
    'recommendation': 'คำแนะนำ',
    'keepTrainingRecommendation': 'ฝึกต่อเนื่องเพื่อรักษาระดับ',

    // Guided Training
    'guidedTraining': 'โปรแกรมฝึกแนะนำ',
    'beginner': 'เริ่มต้น',
    'intermediate': 'ปานกลาง',
    'advanced': 'ขั้นสูง',
    'warmUp': 'วอร์มอัพ',
    'mainTraining': 'ฝึกหลัก',
    'coolDown': 'คูลดาวน์',
    'startProgram': 'เริ่มโปรแกรม',
    'estimatedTime': 'เวลาโดยประมาณ',
    'minutes': 'นาที',
    'trainingSteps': 'ขั้นตอนการฝึก',
    'beginnerProgram': 'โปรแกรมเริ่มต้น',
    'beginnerDesc': 'เหมาะสำหรับผู้เริ่มต้น ฝึกเบาๆ 10 นาที',
    'intermediateProgram': 'โปรแกรมปานกลาง',
    'intermediateDesc': 'เพิ่มความเข้มข้น ฝึก 15 นาที',
    'advancedProgram': 'โปรแกรมขั้นสูง',
    'advancedDesc': 'สำหรับผู้ที่ต้องการท้าทาย ฝึก 20 นาที',
    'warmUpDesc': 'ยืดเหยียดกล้ามเนื้อมือและแขน',
    'mainTrainingDesc': 'ฝึกบีบมือตามจังหวะที่กำหนด',
    'coolDownDesc': 'ผ่อนคลายกล้ามเนื้อหลังฝึก',

    // Achievement
    'achievements': 'รางวัล',
    'unlocked': 'ปลดล็อคแล้ว',
    'locked': 'ยังไม่ปลดล็อค',
    'progress': 'ความคืบหน้า',
    'noAchievements': 'ยังไม่มีรางวัล',

    // Grip Rhythm Game
    'gripRhythm': 'จังหวะบีบมือ',
    'gripRhythmDesc': 'ฝึกบีบมือตามจังหวะโน้ตที่วิ่งลงมา ยิ่งตรงจังหวะ ยิ่งได้คะแนน!',
    'startGame': 'เริ่มเกม',
    'gameOver': 'เกมจบแล้ว!',
    'greatJob': 'ทำได้ดีมาก!',
    'points': 'คะแนน',
    'perfect': 'สมบูรณ์แบบ',
    'good': 'ดี',
    'miss': 'พลาด',
    'playAgain': 'เล่นอีกครั้ง',
    'score': 'คะแนน',
    'difficulty': 'ระดับความยาก',
    'connectESP32': 'เชื่อมต่อ ESP32',
    'connected': 'เชื่อมต่อแล้ว',
    'tapToConnect': 'แตะเพื่อเชื่อมต่อ',
    'scanning': 'กำลังค้นหาอุปกรณ์...',
    'noDevicesFound': 'ไม่พบอุปกรณ์',
    'connectionFailed': 'เชื่อมต่อไม่สำเร็จ',
    'scan': 'ค้นหา',
    'squeezeWhenNoteReaches': 'บีบมือเมื่อโน้ตวิ่งถึงเส้นสี',
    'tapToSqueeze': 'แตะหน้าจอเพื่อบีบมือ',
    'gripRhythmGame': 'เกมจังหวะบีบมือ',
  };

  static String get(String key) {
    return th[key] ?? key;
  }

  static String getWithParams(String key, Map<String, String> params) {
    String result = th[key] ?? key;
    params.forEach((k, v) {
      result = result.replaceAll('{$k}', v);
    });
    return result;
  }
}
